# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: bytecube
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: muul
service: scraper

provider:
  environment:
    ENV: ${self:provider.stage}
  name: aws
  region: ap-south-1
  runtime: nodejs18.x
  stage: ${opt:stage, "dev"}

functions:
  test-scraper:
    memorySize: 1024
    timeout: 60
    image:
      uri: 975050061542.dkr.ecr.ap-south-1.amazonaws.com/scraper:latest
      command:
        - dist/index.handler
