service: scraper

provider:
  environment:
    ENV: ${self:provider.stage}
  name: aws
  region: ap-south-1
  runtime: nodejs20.x
  stage: ${opt:stage, "dev"}

functions:
  test-scraper:
    memorySize: 256
    timeout: 60
    image:
      uri: 975050061542.dkr.ecr.ap-south-1.amazonaws.com/scraper:latest
      command:
        - dist/index.handler
